# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sX7lf9dNEr30tIxamlsmzD2VB_SvlKCk
"""

def kasalik_tashxisi(belgi):
  if belgi == "istima":
    return "Parasetamol iching"
  elif belgi == "bosh og'rig'i":
    return "Tremol iching"
  elif belgi == "grib":
    return "Taylon hot iching"
  elif belgi == "tomog'og'rig'i":
    return "Septolete iching"
  elif belgi == "yo'tal":
    return "Sinekod iching"
  elif belgi == "ozish":
    return "Ducolax iching"
  elif belgi == "ozuvchi allergiya":
     return "Loratadin iching"
  elif belgi == "ko'ngil aynishi":
     return "Motilium iching"
  elif belgi == "tish og'rig'i":
     return "Nurofen iching"
  elif belgi == "qorin og'rig'i":
    return "No-Spa iching"
  else:
    return "Shifokorga murojat qiling "
belgi = input("Kasallik belgisini kiriting: ")
natija = kasalik_tashxisi(belgi)
print(natija)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2

def show_flag(flag):
    if flag == "Rossia":
        rasm1 = cv2.imread("russia.jpg")
        if rasm1 is not None:
            cv2_imshow(rasm1)
            return "Rossiya bayrog'i"
        else:
            return "Rasm topilmadi"
    elif flag == "Fransia":
        rasm2 = cv2.imread("fransia.jpg")
        if rasm2 is not None:
            cv2_imshow(rasm2)
            return "Fransiya bayrog'i"
        else:
            return "Rasm topilmadi"
    elif flag == "Italiya":
        rasm3 = cv2.imread("italy.jpg")
        if rasm3 is not None:
            cv2_imshow(rasm3)
            return "Italiya bayrog'i"
        else:
            return "Rasm topilmadi"
    elif flag == "Polsha":
        rasm4 = cv2.imread("Polsha.jpg")
        if rasm4 is not None:
            cv2_imshow(rasm4)
            return "Polsha bayrog'i"
        else:
            return "Rasm topilmadi"
    elif flag == "Ispaniya":
        rasm5 = cv2.imread("Ispaniya.png")
        if rasm5 is not None:
            cv2_imshow(rasm5)
            return "Ispaniya bayrog'i"
        else:
            return "Rasm topilmadi"
    elif flag == "Shvetsiya":
        rasm6 = cv2.imread("Shvetsiya.png")
        if rasm6 is not None:
            cv2_imshow(rasm6)
            return "Ispaniya bayrog'i"
        else:
            return "Rasm topilmadi"
    else:
        return "Bayroq topilmadi"

flag = input("Yevropa mamlakatlari: ")
natija = show_flag(flag)
print(natija)